#ifndef GAME_SERVER_LC_EXPEDITION_H
#define GAME_SERVER_LC_EXPEDITION_H

enum ELcExpeditionPhase
{
	LC_PHASE_LOBBY_IDLE = 0,
	LC_PHASE_MAP_GENERATING,
	LC_PHASE_DEPARTING,
	LC_PHASE_EXPEDITION,
	LC_PHASE_RETURNING,
};

#endif
