#pragma once

enum
{
    PLAYERCLASS_HUMAN = 0,
    PLAYERCLASS_HOARDINGBUG,
    PLAYERCLASS_BUNKERSPIDER,
    PLAYERCLASS_NUTCRACKER,
    PLAYERCLASS_THUMPER,
    PLAYERCLASS_SNAREFLEA,
    PLAYERCLASS_BRACKEN,

    NUM_PLAYERCLASS,
};